// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqHeQOpXjT3ixZxlkY_5_Bxq85vDhs7w8',
    appId: '1:755303349467:web:089f02327f3e240d2960fe',
    messagingSenderId: '755303349467',
    projectId: 'kendalilampu-234dc',
    authDomain: 'kendalilampu-234dc.firebaseapp.com',
    databaseURL: 'https://kendalilampu-234dc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kendalilampu-234dc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfeAm0LnkBZ934ldZdpBi_QeA0LmvHTmI',
    appId: '1:755303349467:android:c7713208a6bef1762960fe',
    messagingSenderId: '755303349467',
    projectId: 'kendalilampu-234dc',
    databaseURL: 'https://kendalilampu-234dc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kendalilampu-234dc.appspot.com',
  );
}
